name: Build and Push Docker Image to Docker Hub

# This makes the action run automatically every time you push code
on:
  push:
    branches: [ "main" ] # Or your main branch name

jobs:
  build-and-push:
    runs-on: ubuntu-latest # Use a fresh server from GitHub
    steps:
      # 1. Get your code from the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Log in to Docker Hub using the secrets you created
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 3. Build the image and push it to your Docker Hub account
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: lemisteria7/french-basaa-app:latest
